=== M6C/workspace-springboot/src/main/resources/xml/ExtJs/FrmWrk_Servlet.dtd
<?xml version="1.0" encoding="iso-8859-1" ?>
<!-- Element Principale -->
<!ELEMENT ROOT ( QUERY*, BEAN*, FORWARD*, FORWARDERROR*, SERVLET* )>

<!-- Servlet correspondant à une action de l'utilisateur -->
<!ELEMENT SERVLET ( BEAN*, FORWARD*, FORWARDERROR* ) >
<!-- Nom de l'action appelamp;eacute; par la requête -->
<!ATTLIST SERVLET Name CDATA #REQUIRED >
<!-- class d'instance de la servlet -->
<!ATTLIST SERVLET Class CDATA #IMPLIED >
<!-- Page de redirection (Si commence par # alors recherche la valeur de la
chaine suivant dans la requête pour la detination de la redirection -->
<!ATTLIST SERVLET Target CDATA #IMPLIED >
<!-- Page de redirection en cas d'erreur (Si commence par # alors recherche la
valeur de la chaine suivant dans la requête pour la detination de la redirection -->
<!ATTLIST SERVLET TargetError CDATA #IMPLIED >
<!-- Indique si la l'accès à l'action requier une authentification (Value: "true" "false") [optional : by default "true"]
(Si commence par # alors recherche la valeur de la chaine suivant dans la requête pour la detination de la redirection -->
<!ATTLIST SERVLET Authentification ( true | false ) #IMPLIED >

<!-- Bean de Stockage des donnamp;eacute;es Retournamp;eacute;e par la base -->
<!ELEMENT BEAN ( PARAM*, QUERY* ) >
<!-- Nom du bean utilisamp;eacute; pour le stockage dans le Scope -->
<!ATTLIST BEAN Name CDATA #REQUIRED >
<!-- Class d'instance du bean -->
<!ATTLIST BEAN Class CDATA #IMPLIED >
<!-- Scope d'accessibilitamp;eacute; du bean (Value: "session" "request") [optional : by defaut "request"] -->
<!ATTLIST BEAN Scope ( request | session ) #IMPLIED >
<!-- Nom du service qui va être executer après la cramp;eacute;ation du bean [optional] -->
<!ATTLIST BEAN Service CDATA #IMPLIED >

<!-- Parametre à passer à la requete SQL -->
<!ELEMENT PARAM EMPTY >
<!-- Nom du paramêtre SQL. Utilisamp;eacute; pour recuperer la valeur soit en "session"
soit en "request" soit à partir d'un bean ( si l'attribut bean est defini-->
<!ATTLIST PARAM Name CDATA #REQUIRED >
<!-- Type de parametre à passer à la requete SQL ( LIST | STRING | CURSOR | INTEGER | BOOLEAN | OBJECT | DATE | TIME | DATETIME ) -->
<!ATTLIST PARAM Type CDATA #IMPLIED >
<!-- Position du paramtre dans la requete [optional] par defaut position dans le fichier XML -->
<!ATTLIST PARAM Index CDATA #IMPLIED >
<!-- Defini si le parametre sera passamp;eacute; en entramp;eacute;e à la requête
SQL ou stockera le resultat [optional] par defaut "IN"-->
<!ATTLIST PARAM InOut ( OUT | IN ) #IMPLIED >
<!-- Valeur par defaut du paramêtre [optional] par defaut "null" -->
<!ATTLIST PARAM Default CDATA #IMPLIED >
<!-- Class de stockage du resultat de la requete SQL
dans le cas ou l'attribut InOut serait "OUT"-->
<!ATTLIST PARAM Class CDATA #IMPLIED >
<!-- Nom du bean qui contiend la valeur du paramêtre [optional] -->
<!ATTLIST PARAM Bean CDATA #IMPLIED >
<!-- Indique si le parametre est synchronise avec une valeur la requette [optional] par defaut "TRUE" -->
<!ATTLIST PARAM Synchronize (TRUE | FALSE) #IMPLIED >
<!-- Format de la donnée en entrée de la requête Ex: 'AAAA-MM-JJ HH:MM:SS' pour une date '2000-12-31 23:59:59' -->
<!ATTLIST PARAM FormatIn CDATA #IMPLIED >

<!-- Requête à executer en base et dont le resultat est stockamp;eacute; dans le bean -->
<!ELEMENT QUERY ( #PCDATA ) >
<!-- Nom de la requête -->
<!ATTLIST QUERY Name CDATA #IMPLIED >
<!-- Type de requete à executer -->
<!ATTLIST QUERY Type (EXECUTE | STORED_PROCEDURE | QUERY | HIBERNATE) #REQUIRED >
<!-- Nombre de parametre à passer à la requête [optional] par defaut 0 -->
<!ATTLIST QUERY ParameterCount CDATA #IMPLIED >

<!-- Redirection normale de la servlet -->
<!ELEMENT FORWARD EMPTY >
<!-- Nom de la redirection -->
<!ATTLIST FORWARD Name ID #IMPLIED >
<!-- Condition de redirection (redirection si l'amp;eacute;valuation de la condition est true)-->
<!ATTLIST FORWARD Condition CDATA #IMPLIED >
<!-- Valeur de remplacement des null du champ 'Condition' -->
<!ATTLIST FORWARD ReplaceNullBy CDATA #IMPLIED >
<!-- Adresse de redirection -->
<!ATTLIST FORWARD Target CDATA #IMPLIED >

<!-- Redirection en cas d'erreur de la servlet -->
<!ELEMENT FORWARDERROR EMPTY >
<!-- Nom de la redirection -->
<!ATTLIST FORWARDERROR Name ID #IMPLIED >
<!-- Condition de redirection (redirection si l'amp;eacute;valuation de la condition est true)-->
<!ATTLIST FORWARDERROR Condition CDATA #IMPLIED >
<!-- Valeur de remplacement des null du champ 'Condition' -->
<!ATTLIST FORWARD ReplaceNullBy CDATA #IMPLIED >
<!-- Adresse de redirection -->
<!ATTLIST FORWARDERROR Target CDATA #IMPLIED >

=== M6C/workspace-springboot/src/main/resources/xml/FrmWrk_Servlet.xml
<!DOCTYPE ROOT SYSTEM "FrmWrk_Servlet.dtd">
<ROOT>
    <BEAN Name="beanSchemaList" Service="framework.service.SrvFindList" Class="framework.beandata.BeanFindList" Scope="request">
        <QUERY Type="QUERY">SELECT * FROM information_schema.SCHEMATA</QUERY>
    </BEAN>
    <BEAN Name="beanTableList" Service="framework.service.SrvFindList" Class="framework.beandata.BeanFindList" Scope="request">
        <PARAM Name="schema" Type="STRING"/>
        <QUERY Type="QUERY" ParameterCount="1">SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA = ?</QUERY>
    </BEAN>
    <BEAN Name="beanColumnList" Service="framework.service.SrvFindList" Class="framework.beandata.BeanFindList" Scope="request">
        <PARAM Name="schema" Type="STRING"/>
        <PARAM Name="table" Type="STRING"/>
        <QUERY Type="QUERY" ParameterCount="1">SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ?</QUERY>
    </BEAN>
    <BEAN Name="beanFkColumnList" Service="framework.service.SrvFindList" Class="framework.beandata.BeanFindList" Scope="request">
        <PARAM Name="schema" Type="STRING"/>
        <PARAM Name="table" Type="STRING"/>
        <PARAM Name="column" Type="STRING"/>
        <QUERY Type="QUERY" ParameterCount="1">SELECT REFERENCED_TABLE_SCHEMA AS TABLE_SCHEMA, REFERENCED_TABLE_NAME AS TABLE_NAME, REFERENCED_COLUMN_NAME AS COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND COLUMN_NAME = ?</QUERY>
    </BEAN>
    <SERVLET Name="Index" Target="/Web/Page/index.jsp" Authentification="false"/>
    <SERVLET Name="Home" Target="/Web/Page/home.jsp"/>
    <SERVLET Name="HomePopup" Target="/Web/Page/home_popup.jsp"/>
    <SERVLET Name="IndexLoginValider" Target="/Web/Page/home_popup.jsp" TargetError="/Web/Page/index.jsp" Authentification="false">
        <BEAN Name="BeanAuthentification" Scope="request" Service="workspace.service.SrvIndexLoginValider">
            <PARAM Name="login" Type="STRING"/>
            <PARAM Name="password" Type="STRING"/>
        </BEAN>
    </SERVLET>
    <SERVLET Name="EditorJavaPage" Target="/Web/PageExtJs/EditorJava/Page.jsp" TargetError="/Web/Page/index.jsp">
        <BEAN Name="BeanEditorJava" Scope="request" Service="workspace.service.SrvEditorJavaPage">
            <PARAM Name="application" Type="STRING"/>
            <PARAM Name="pathToExpand" Type="STRING"/>
            <PARAM Name="FileName" Type="STRING"/>
        </BEAN>
    </SERVLET>
    <SERVLET Name="EditorJavaPageSave" Target="/Web/Page/EditorJava/Page.jsp" TargetError="/Web/Page/index.jsp">
        <BEAN Name="BeanEditorJava" Scope="request" Service="workspace.service.SrvEditorJavaValider">
            <PARAM Name="application" Type="STRING"/>
            <PARAM Name="FileEditor" Type="STRING"/>
            <PARAM Name="FileName" Type="STRING"/>
            <PARAM Name="pathToExpand" Type="STRING"/>
            <PARAM Name="navIndex" Type="STRING"/>
            <PARAM Name="navNbRow" Type="STRING"/>
        </BEAN>
    </SERVLET>
    <SERVLET Name="PageFileEditor" Target="/Web/Page/Common/PageFileEditor.jsp" TargetError="/Web/Page/index.jsp">
        <BEAN Name="BeanEditorJava" Scope="request" Service="workspace.service.SrvEditorJavaPage">
            <PARAM Name="application" Type="STRING"/>
        </BEAN>
    </SERVLET>
    <SERVLET Name="PageFileEditorValider" Target="/Web/Page/Common/PageFileEditor.jsp" TargetError="/Web/Page/index.jsp">
        <BEAN Name="BeanEditorJava" Scope="request" Service="workspace.service.SrvEditorJavaValider">
            <PARAM Name="application" Type="STRING"/>
            <PARAM Name="FileEditor" Type="STRING"/>
            <PARAM Name="FileName" Type="STRING"/>
            <PARAM Name="pathToExpand" Type="STRING"/>
            <PARAM Name="navIndex" Type="STRING"/>
            <PARAM Name="navNbRow" Type="STRING"/>
        </BEAN>
    </SERVLET>
    <SERVLET Name="EditorJavaPageNew" Target="/Web/Page/Common/PageNew.jsp" TargetError="/Web/Page/index.jsp"/>
    <SERVLET Name="EditorJavaPageNewValider" Target="/Web/Page/Common/PageNew.jsp" TargetError="/Web/Page/index.jsp">
        <BEAN Name="BeanNewFile" Scope="request" Service="workspace.service.SrvEditorJavaNew">
            <PARAM Name="application" Type="STRING"/>
            <PARAM Name="Type" Type="STRING"/>
            <PARAM Name="Path" Type="STRING"/>
            <PARAM Name="Name" Type="STRING"/>
        </BEAN>
    </SERVLET>
    <SERVLET Name="EditorJavaPageCompile" Target="/Web/Page/Common/PageCompile.jsp" TargetError="/Web/Page/index.jsp"/>
    <SERVLET Name="EditorJavaPageCompileValider" Target="/Web/Page/Common/PageCompile.jsp" TargetError="/Web/Page/index.jsp">
        <BEAN Name="BeanNewFile" Scope="request" Service="workspace.service.SrvEditorJavaCompile">
            <PARAM Name="application" Type="STRING"/>
            <PARAM Name="pathSrc" Type="STRING"/>
            <PARAM Name="pathDst" Type="STRING"/>
            <PARAM Name="type" Type="STRING"/>
        </BEAN>
    </SERVLET>
    <SERVLET Name="EditorJavaPageCompileClean" Target="/Web/Page/Common/PageMessage.jsp" TargetError="/Web/Page/index.jsp">
        <BEAN Name="BeanNewFile" Scope="request" Service="workspace.service.SrvEditorJavaCompileClean">
            <PARAM Name="application" Type="STRING"/>
            <PARAM Name="type" Type="STRING"/>
        </BEAN>
    </SERVLET>
    <SERVLET Name="EditorJavaPageCompileDirect" Target="/Web/Page/Common/PageMessage.jsp" TargetError="/Web/Page/index.jsp">
        <BEAN Name="BeanNewFile" Scope="request" Service="workspace.service.SrvEditorJavaCompile">
            <PARAM Name="application" Type="STRING"/>
            <PARAM Name="pathSrc" Type="STRING"/>
            <PARAM Name="pathDst" Type="STRING"/>
            <PARAM Name="type" Type="STRING"/>
        </BEAN>
    </SERVLET>
    <SERVLET Name="EditorJavaPageJar" Target="/Web/Page/Common/PageJar.jsp" TargetError="/Web/Page/index.jsp"/>
    <SERVLET Name="EditorJavaPageJarValider" Target="/Web/Page/Common/PageJar.jsp" TargetError="/Web/Page/index.jsp">
        <BEAN Name="BeanNewFile" Scope="request" Service="workspace.service.SrvEditorJavaPackage">
            <PARAM Name="application" Type="STRING"/>
            <PARAM Name="package" Type="STRING"/>
            <PARAM Name="type" Type="STRING"/>
        </BEAN>
    </SERVLET>
    <SERVLET Name="EditorJavaPageWar" Target="/Web/Page/Common/PageWar.jsp" TargetError="/Web/Page/index.jsp"/>
    <SERVLET Name="EditorJavaPageWarValider" Target="/Web/Page/Common/PageWar.jsp" TargetError="/Web/Page/index.jsp">
        <BEAN Name="BeanNewFile" Scope="request" Service="workspace.service.SrvEditorJavaPackage">
            <PARAM Name="application" Type="STRING"/>
            <PARAM Name="package" Type="STRING"/>
            <PARAM Name="type" Type="STRING"/>
        </BEAN>
    </SERVLET>
    <SERVLET Name="EditorJavaPageWarClean" Target="/Web/Page/Common/PageWarClean.jsp" TargetError="/Web/Page/index.jsp"/>
    <SERVLET Name="EditorJavaPageWarCleanValider" Target="/Web/Page/Common/PageWarClean.jsp" TargetError="/Web/Page/index.jsp">
        <BEAN Name="BeanNewFile" Scope="request" Service="workspace.service.SrvEditorJavaPackageClean">
            <PARAM Name="application" Type="STRING"/>
            <PARAM Name="package" Type="STRING"/>
            <PARAM Name="type" Type="STRING"/>
        </BEAN>
    </SERVLET>
    <SERVLET Name="EditorJavaPageZip" Target="/Web/Page/Common/PageZip.jsp" TargetError="/Web/Page/index.jsp"/>
    <SERVLET Name="EditorJavaPageZipValider" Target="/Web/Page/Common/PageZip.jsp" TargetError="/Web/Page/index.jsp">
        <BEAN Name="BeanNewFile" Scope="request" Service="workspace.service.SrvEditorJavaZip">
            <PARAM Name="application" Type="STRING"/>
            <PARAM Name="pathSrc" Type="STRING"/>
            <PARAM Name="pathDst" Type="STRING"/>
            <PARAM Name="fileName" Type="STRING"/>
        </BEAN>
    </SERVLET>
    <SERVLET Name="EditorJavaPageCopyMove" Target="/Web/Page/Common/PageCopyMove.jsp" TargetError="/Web/Page/index.jsp"/>
    <SERVLET Name="EditorJavaPageCopyMoveValider" Target="/Web/Page/Common/PageCopyMove.jsp" TargetError="/Web/Page/index.jsp">
        <BEAN Name="BeanCopyMove" Scope="request" Service="workspace.service.SrvEditorJavaCopyMove">
            <PARAM Name="application" Type="STRING"/>
            <PARAM Name="pathSrc" Type="STRING"/>
            <PARAM Name="pathDst" Type="STRING"/>
            <PARAM Name="nameDst" Type="STRING"/>
            <PARAM Name="operation" Type="STRING"/>
        </BEAN>
    </SERVLET>
    <SERVLET Name="EditorJavaPageXmlXsl" Target="/Web/Page/Common/PageXmlXsl.jsp" TargetError="/Web/Page/index.jsp"/>
    <SERVLET Name="EditorJavaPageXmlXslValider" Target="/Web/Page/Common/PageText.jsp" TargetError="/Web/Page/index.jsp">
        <BEAN Name="BeanXmlXsl" Scope="request" Service="workspace.service.SrvEditorJavaXmlXsl">
            <PARAM Name="application" Type="STRING"/>
            <PARAM Name="pathXml" Type="STRING"/>
            <PARAM Name="xmlName" Type="STRING"/>
            <PARAM Name="xmlScope" Type="STRING"/>
            <PARAM Name="pathXsl" Type="STRING"/>
            <PARAM Name="paramXsl" Type="STRING"/>
            <PARAM Name="xslParamName" Type="STRING"/>
            <PARAM Name="resultName" Type="STRING" Default="xmlResult"/>
        </BEAN>
    </SERVLET>
    <SERVLET Name="EditorJavaPageXmlXsl" Target="/Web/Page/Common/PageXmlXsl.jsp" TargetError="/Web/Page/index.jsp"/>
    <SERVLET Name="EditorJavaPageXmlXslValider" Target="/Web/Page/Common/PageText.jsp" TargetError="/Web/Page/index.jsp">
        <BEAN Name="BeanXmlXsl" Scope="request" Service="workspace.service.SrvEditorJavaXmlXsl">
            <PARAM Name="application" Type="STRING"/>
            <PARAM Name="pathXml" Type="STRING"/>
            <PARAM Name="xmlName" Type="STRING"/>
            <PARAM Name="xmlScope" Type="STRING"/>
